### ISSUE TITLE
API connecting issue

### ISSUE THREAD

**Issue by lotuspiggy** [LightningPiggy/lightningpiggy.github.io#6]
Hi,

Somehow I can't get Lightning Piggy to show the wallet on its screen and keep getting a Get wallet error. 

I've tried everything, switching wifi or 5G networks, VPN on and off, different Lightning Piggy versions, multiple rebooting of every hardware device involved, but nothing seems to solve the problem. 

On LNBits everything looks fine, wallet is up and running, sats have been received and it shows the amount. But somewhere in the API connection it is not going good, as the attached logs will show. 

Hopefully someone can see the issue and knows a solution. Oink! 

Thanks.

[05-04-24 esp-web-tools-logs (9).txt](https://github.com/LightningPiggy/lightningpiggy.github.io/files/14884428/05-04-24.esp-web-tools-logs.9.txt)
<img width="1381" alt="Scherm­afbeelding 2024-04-05 om 12 36 40" src="https://github.com/LightningPiggy/lightningpiggy.github.io/assets/165806549/a0a5104f-51a4-4239-a0eb-192bf88d1ff3">
<img width="1376" alt="Scherm­afbeelding 2024-04-05 om 12 37 14" src="https://github.com/LightningPiggy/lightningpiggy.github.io/assets/165806549/37e89f35-8e66-4f87-9a4a-6f83548f5683">
<img width="1380" alt="Scherm­afbeelding 2024-04-05 om 12 37 36" src="https://github.com/LightningPiggy/lightningpiggy.github.io/assets/165806549/1d2f118e-0a29-4227-afba-33290b49a794">

**Comment by ThomasFarstrike** [comment]
AAAH I see it now! It's trying to resolve "https://legend.lnbits.com/" as a DNS name instead of "legend.lnbits.com"!

So in the configuration, you need to specify the hostname (legend.lnbits.com as in the hint), not the URL...

Thank you for reporting and sorry I didn't catch this sooner!
